#!/usr/bin/env python

from gi.repository import Gtk, Vte, Gdk
from gi.repository import GLib
import os

terminal     = Vte.Terminal()
terminal.fork_command_full(
    Vte.PtyFlags.DEFAULT,
    os.environ['HOME'],
    ["/usr/bin/argon-update"],
    [],
    GLib.SpawnFlags.DO_NOT_REAP_CHILD,
    None,
    None,
    )

win = Gtk.Window(title="Argon - System Update")
win.set_icon_from_file('/usr/share/argon/argon.png')
win.set_position(Gtk.WindowPosition.CENTER)
win.connect('delete-event', Gtk.main_quit)
win.add(terminal)
win.show_all()
terminal.set_color_foreground_rgba(Gdk.RGBA(.09, .58, .82, 1))
terminal.set_color_background_rgba(Gdk.RGBA(0, 0, 0, 1))

Gtk.main()
