#!/usr/bin/env python

from gi.repository import Gtk, Vte
from gi.repository import GLib
import os

terminal     = Vte.Terminal()
terminal.fork_command_full(
    Vte.PtyFlags.DEFAULT,
    os.environ['HOME'],
    ["/usr/bin/argon-update"],
    [],
    GLib.SpawnFlags.DO_NOT_REAP_CHILD,
    None,
    None,
    )

win = Gtk.Window(title="Argon - System Update")
win.set_position(Gtk.WindowPosition.CENTER)
win.connect('delete-event', Gtk.main_quit)
win.add(terminal)
win.show_all()

Gtk.main()
