#!/bin/bash
echo "-------------"
echo "System Update"
echo "-------------"
echo ""
pacaur -Syu
echo ""
echo "------------------------------------"
echo "close this window to return to Argon"
echo "------------------------------------"
