#!/bin/bash
echo "------------------------------"
echo "Top-level Owner-added Packages"
echo "------------------------------"
echo ""
package=$(</etc/argon/package)
pacaur -Rs $package
echo ""
echo "------------------------------------"
echo "Close this window to return to Argon"
echo "------------------------------------"
