#!/bin/bash
echo "-----------------------------"
echo "Top-level User-added Packages"
echo "-----------------------------"
echo ""
comm -23 <(comm -23 <(pacman -Qtq) <(pacman -Qgq base base-devel | sort)) <(cat /etc/argon/top-remove | sort) > /etc/argon/top-temp
cat /etc/argon/top-add >> /etc/argon/top-temp
cat /etc/argon/top-temp | sort > top-final
echo ""
echo "------------------------------------"
echo "close this window to return to Argon"
echo "------------------------------------"
