#!/bin/bash
echo "--------------------"
echo "Package Installation"
echo "--------------------"
echo ""
package=$(</etc/argon/package)
pacaur -S $package
echo ""
echo "------------------------------------"
echo "close this window to return to Argon"
echo "------------------------------------"
