#!/bin/bash
echo "    ,"
echo "   /-\\-------------------"
echo "  //_\\\\   System Update  \\"
echo " /// \\\\\\-------------------"
echo "/.-' '-.\\"
echo ""
pacaur -Syu
IFS=$'\r\n' config=($(cat /etc/argon/config))
echo ${config[3]} > /etc/argon/message
echo ""
echo "    ,"
echo "   /-\\-----------------------------------------------------"
echo "  //_\\\\   process complete, you may now close this window  \\"
echo " /// \\\\\\-----------------------------------------------------"
echo "/.-' '-.\\"

