#!/usr/bin/python

from gi.repository import Gtk
import os

class GridWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title="Argon Package Manager")
        self.set_border_width(8)
        self.set_position(Gtk.WindowPosition.CENTER)
        self.set_icon_from_file('/usr/share/argon/argon.png')
        grid = Gtk.Grid(column_homogeneous=True,column_spacing=8,row_spacing=8)
        self.add(grid) 

        self.entry1 = Gtk.Entry()
        self.entry1.connect("activate", self.button1sig)

        self.button1 = Gtk.Button("Install")
        self.button1.connect("clicked", self.button1sig)

        self.entry2 = Gtk.Entry()
        self.entry2.connect("activate", self.button2sig)

        self.button2 = Gtk.Button("Remove")
        self.button2.connect("clicked", self.button2sig)

        self.button5 = Gtk.Button("TOP List")
        self.button5.connect("clicked", self.button5sig)

        self.button3 = Gtk.Button("Configure Notifier")
        self.button3.connect("clicked", self.button3sig)

        self.button4 = Gtk.Button("Update System")
        self.button4.connect("clicked", self.button4sig)

        grid.add(self.entry1)
        grid.attach(self.button1,1,0,1,1)
        grid.attach(self.entry2,0,1,1,1)
        grid.attach(self.button2,1,1,1,1)
        grid.attach(self.button3,0,2,1,1)
        grid.attach(self.button5,1,2,1,1)
        grid.attach(self.button4,0,3,2,1)

    def button1sig(self, configalter):
        package = self.entry1.get_text()
        os.system("echo %s > /etc/argon/package" % (package))
        os.system("argon-install-vte")
        self.entry1.set_text("")
        self.entry2.set_text("")

    def button2sig(self, configalter):
        package = self.entry2.get_text()
        os.system("echo %s > /etc/argon/package" % (package))
        os.system("argon-remove-vte")
        self.entry1.set_text("")
        self.entry2.set_text("")

    def button5sig(self, configalter):
        os.system("argon-list-vte")
        self.entry1.set_text("")
        self.entry2.set_text("")

    def button3sig(self, configalter):
        os.system("argon-notifier-config")
        self.entry1.set_text("")
        self.entry2.set_text("")

    def button4sig(self, configalter):
        os.system("argon-update-vte")
        self.entry1.set_text("")
        self.entry2.set_text("")

win = GridWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
