#!/bin/bash
echo "---------------"
echo "Package Removal"
echo "---------------"
echo ""
package=$(</etc/argon/package)
pacaur -Rs $package
echo ""
echo "------------------------------------"
echo "close this window to return to Argon"
echo "------------------------------------"
